
server:
  port: 9522

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9521/eureka/

spring:
  application:
    name: lekima-admin
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/rspsdb?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybaits/mapper/*.xml
  config-location:  classpath:mybatis-config.xml

